# input string 
string= "CGCGACGGGTGAGGTCCCGGGCTAGACAGAAGGCACATCCACTCTATCGTTAGCCAGGGGACTAGAATAGGTGGGCTGATATTCCCCCCGATCACTGTAGACACATCGGAAAATCTCCATGAAACTGAAGAACGGGCATACCAACTGCAAGTGAATCTAACCAAGCCGTGACGGCGGCCGGGCATACTCAATTGATAGTCCTATTTGTTTACAGCCCAGTCGCCGAGGTGACCGAATTAACTGTTCCATCGCGGTTAGCTTACGTATATAAAAGAAGCGCGGACTCTTAGTAACCCCTCTGAACAGAACACATAAGGGTCTAGAAAGTAGTAACGATATGTTTTATTACTCTAGTGACAAATTGCAATGCTATCCTGTTTGTGCGGTCAGGGAACGGTGGAGCTGAATGTGAATGCAACTATAAGAGTGATTCCCTCTGGATCCAACTGGTGGCTTTGTCCGCACTTGTTCTTTGGTCTCGTTTAACACGTCAACGCTGTCGGATGCCTGGTAGATGCGGTCTTGCTCTGTTTGGCTCATATAGGTCTGTTGCTAGTTGAAGGCAAGAAGGTTTCGTATAAAGGACTATCGCACAGTCGACGATCTGTCTGTGAGGTTCGCGAGCGAGGGCGGAAATCCAAGGCACTCTGGTTTGCGCCATCTTAGTGACATATTCGCTGCTTGTCATTTCGATAATGCAACATTCCCGGGTTCGCGCTCACATACCTTACAGAAGTAAAGGTCTAATCAACCCGGTCTTCGGGAGAGGTCGTCAGTACGTAAATAATTTAAGTTACCAGAACTCCTCTAGACAATAACACGTCCACCAGAGGCATGAAATTCAATTCACCCATAACAATTGCCATCATCGGT"
a_count= 0
c_count= 0
g_count= 0
t_count= 0

# checking for letter in string
for i in string:

    if i == "A" :
        a_count += 1 

    elif i == "C":
        c_count += 1

    if i == "G":
        g_count += 1

    if i == "T":
        t_count+= 1



print(a_count, "A nucleotides in string")
print(c_count, "C nucleotides in string")
print(g_count, "G nucleotides in string")
print(t_count, "T nucleotides in string")

print(a_count, c_count, g_count, t_count)